### ISSUE TITLE
Leere Text-Tabelle ist nicht leer!

### ISSUE THREAD

**Issue by lucdesign** [MetaModels/attribute_translatedtabletext#10]
Issue gewandert von bundle_attributes:

Wenn man eine translated Text-Tabelle einmal befüllt hat und später alle Elemente wieder löscht, bleibt eine "Geisterzeile" mit Leerstrings als Werten übrig. Im Template wird das als nicht-leeres Array erkannt.
Man kann diesen Fehler provisorisch mit der Abfrage

``` php
<?php if ($this->raw[0][0]['value'] !== "") : ?>
```

abfangen. Das gleiche muss man aber auch prüfen, wenn man die Zeilen zählen will!

**Comment by discordier** [comment]
Oh, das ist mir hier nun klar warum...
Das ist ja gar nicht implementiert.
https://github.com/MetaModels/attribute_translatedtabletext/blob/2fec6bf4f8190668854b7cbf6578a4e9756774a2/src/MetaModels/Attribute/TranslatedTableText/TranslatedTableText.php#L348

**Comment by lucdesign** [comment]
Ich hab das nochmal gecheckt. Auch im einsprachigen table text ist das Problem exakt das selbe. Soll ich das issue dort nochmal anlegen? Issues moven gaht ja nur manuell ...

**Comment by MacKP** [comment]
Ja, bitte da auch noch posten und refernzieren.

**Comment by lucdesign** [comment]
Posten gerne, aber wie referenzieren? Bin leider noch immer ein Github-Nackerbatzl.

**Comment by xantippe** [comment]
@discordier ist der Bug noch aktuell?

**Comment by discordier** [comment]
Yop, ist immer noch nicht implementiert. Siehe oben verlinkte Codestelle

**Comment by zonky2** [comment]
anscheinend doch (18. Feb.) https://github.com/MetaModels/attribute_translatedtabletext/commit/5dfcf97adf2ec5840746352010781e218a880039

**Comment by discordier** [comment]
Wurde von @stefanheimes aber erst im Maerz gemerged 06107207637a3ac7421a3fac693bc4275d93ce07.
Ist also nun behoben.
