### ISSUE TITLE
Wrong datatype

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/attribute_translatedtabletext#11]
https://github.com/MetaModels/attribute_translatedtabletext/blob/master/src/MetaModels/Attribute/TranslatedTableText/TranslatedTableText.php#L70

See the line, both values are strings, so the array_key_exists is a little bit wrong.

**Comment by xantippe** [comment]
@stefanheimes kann Ticket geschlossen werden?

https://github.com/MetaModels/attribute_translatedtabletext/commit/3f0485c8fef9db981ee17764d3c62caeaafcee93

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@stefanheimes could you please have a final look at this and tell if your issue has been resolved?
