### ISSUE TITLE
More than 10 columns?

### ISSUE THREAD

**Issue by design23** [MetaModels/attribute_translatedtabletext#8]
Is it possible to add more than 10 columns?

**Comment by discordier** [comment]
This is currently a hardcoded default.
I wonder why it is in place, @stefanheimes do you have a clue?

You should be able to circumvent it by putting the following into your dca_config.php:
```php
$GLOBALS['TL_DCA']['tl_metamodel_attribute']['fields']['tabletext_quantity_cols']['options'] = range(1, 50);
```
Where the 50 is the maximum that shall be selectable.

**Comment by stefanheimes** [comment]
I think  you mean this https://github.com/MetaModels/attribute_translatedtabletext/blob/tng/contao/dca/tl_metamodel_attribute.php#L32.

**Comment by discordier** [comment]
Yep, why is it limited to 10? Was there a reason or is it just a rule of thumb?

**Comment by stefanheimes** [comment]
Because we think it is enough and there is no space. :)

**Comment by discordier** [comment]
@design23 that question of @stefanheimes was in your direction.

**Comment by design23** [comment]
Oh, sorry. Didn't realise that :)
For the moment, 11 would be enough. I used the dca config solution which works like charm. 
For the future, a configurable solution would be awesome.

**Comment by zonky2** [comment]
new URL: https://github.com/MetaModels/attribute_translatedtabletext/blob/master/contao/dca/tl_metamodel_attribute.php#L32
